# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6amdy9QsiPmm8Pk3tnTmuu506mbIFuD
"""

#PyTrends is a Python library that functions as an unofficial API (Application Programming Interface) for Google Trends

!pip install PyTrends matplotlib seaborn plotly

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from pytrends.request import TrendReq

#setup pytrend library and keyword define

pytrends=TrendReq(hl='en-US',tz=360)
#hl = language
#tz = time zone
keyword="cloud computing"

# we can change the keyword according to requirements

#data request
pytrends.build_payload([keyword],cat=0, timeframe='today 12-m' , geo='', gprop='')
#cat=category
# geo='' need data at global level
# gprop=''  needs data only form google data npt frpm news, youtube

"""country wise interest"""

pytrends.build_payload([keyword],cat=0, timeframe='today 12-m' , geo='', gprop='')
region_data=pytrends.interest_by_region()
region_data=region_data.sort_values(by=keyword, ascending=False).head(15)

plt.figure(figsize=(10,6))
sns.barplot(x=region_data[keyword],y=region_data.index,palette="Blues_d")
plt.title(f"Top Countries searching for '{keyword}'")
plt.xlabel("Interest Value")
plt.ylabel("Countries")
plt.show()

"""World Map"""

region_data=region_data.reset_index()
fig=px.choropleth(region_data, locations='geoName',locationmode='country names', color= keyword,title=f"Search interest for '{keyword} by Country", color_continuous_scale='Oranges')
fig.show()



"""Time wise interest"""

time_df=pytrends.interest_over_time()

plt.figure(figsize=(12,6))
plt.plot(time_df.index, time_df[keyword],marker='o', color='red')
plt.title(f"Interest Over Time for '{keyword}'")
plt.xlabel("Date")
plt.ylabel("Interest Value")
plt.grid(True)
plt.show()

# multiple keyword campare

kw_list=["cloud computing","data science","machine learning"]

pytrends.build_payload(kw_list, cat=0, timeframe='today 12-m', geo='', gprop='')

compare_df=pytrends.interest_over_time()

plt.figure(figsize=(12,6))

for kw in kw_list:
    plt.plot(compare_df.index, compare_df[kw], marker='o', label=kw)

plt.title("Interest Over Time Comparison")
plt.xlabel("Date")
plt.ylabel("Interest Value")
plt.legend()